# Generated by Django 4.1.5 on 2023-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdata',
            name='eta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='numPass',
            field=models.IntegerField(),
        ),
    ]
