# Generated by Django 4.1.5 on 2023-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_busdata_eta_alter_busdata_numpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaja', models.CharField(max_length=100)),
                ('numPass', models.IntegerField()),
                ('eta', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BusData',
        ),
    ]
